0,SyntaxError,"unexpected EOF while parsing (<ipython-input-10-c7b7223ecd08>, line 1)",0,,2023-01-23 15:10:18.461211,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-10-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
1,SyntaxError,"unexpected EOF while parsing (<ipython-input-11-c7b7223ecd08>, line 1)",0,,2023-01-23 15:10:52.436835,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-11-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
2,NameError,name 'eleven' is not defined,5,,2023-01-23 15:11:15.853408,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-20-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
3,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-01-23 15:12:48.114978,"[('grader.check(""q3_1_2"")', 1), ('raise e', 193)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-25-f6c31d438c41>"", line 1, in <module>', '    grader.check(""q3_1_2"")', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 193, in event_logger', '    raise e', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 184, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
4,ValueError,Expected a notebook file named 'lab01-Copy.ipynb' but no such file found,0,,2023-01-23 15:17:15.880139,"[('grader.check(""q0"")', 1), ('raise e', 193)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-29-b54ec3250167>"", line 1, in <module>', '    grader.check(""q0"")', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 193, in event_logger', '    raise e', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 184, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/notebook.py"", line 203, in check', '    self._resolve_nb_path(None, fail_silently=True),', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/notebook.py"", line 174, in _resolve_nb_path', '    raise ValueError(f""Expected a notebook file named \'{nb_path}\' but no such file found"")', ""ValueError: Expected a notebook file named 'lab01-Copy.ipynb' but no such file found""]"
5,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-01-23 15:18:22.963082,"[('grader.check(""q0"")', 1), ('raise e', 193)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-32-b54ec3250167>"", line 1, in <module>', '    grader.check(""q0"")', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 193, in event_logger', '    raise e', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 184, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
6,SyntaxError,"unexpected EOF while parsing (<ipython-input-13-c7b7223ecd08>, line 1)",0,,2023-01-23 15:22:05.319431,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-13-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
7,SyntaxError,"unexpected EOF while parsing (<ipython-input-14-c7b7223ecd08>, line 1)",0,,2023-01-23 15:24:23.653310,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-14-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
8,SyntaxError,"unexpected EOF while parsing (<ipython-input-16-c7b7223ecd08>, line 1)",0,,2023-01-23 15:25:47.995190,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-16-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
9,SyntaxError,"unexpected EOF while parsing (<ipython-input-18-c7b7223ecd08>, line 1)",0,,2023-01-23 15:26:13.968980,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-18-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
10,SyntaxError,"unexpected EOF while parsing (<ipython-input-20-c7b7223ecd08>, line 1)",0,,2023-01-23 15:26:20.690937,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-20-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
11,SyntaxError,"unexpected EOF while parsing (<ipython-input-22-c7b7223ecd08>, line 1)",0,,2023-01-23 15:30:06.885561,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-22-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
12,SyntaxError,"unexpected EOF while parsing (<ipython-input-24-c7b7223ecd08>, line 1)",0,,2023-01-23 15:30:44.954056,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-24-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
13,SyntaxError,"unexpected EOF while parsing (<ipython-input-10-c7b7223ecd08>, line 1)",0,,2023-01-23 15:32:48.295201,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-10-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
14,SyntaxError,"unexpected EOF while parsing (<ipython-input-22-c7b7223ecd08>, line 1)",0,,2023-01-23 16:03:15.004087,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-22-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
15,NameError,name 'eleven' is not defined,0,,2023-01-23 16:09:41.561586,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-31-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
16,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-01-23 16:10:08.520187,"[('grader.check(""q3_1_2"")', 1), ('raise e', 193)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-36-f6c31d438c41>"", line 1, in <module>', '    grader.check(""q3_1_2"")', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 193, in event_logger', '    raise e', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 184, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
17,RuntimeError,Malformed test file: does not define the global variable 'OK_FORMAT',0,,2023-01-23 16:59:26.833526,"[('grader.check(""q0"")', 1), ('raise e', 193)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-43-b54ec3250167>"", line 1, in <module>', '    grader.check(""q0"")', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 193, in event_logger', '    raise e', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/utils.py"", line 184, in event_logger', '    question, results, shelve_env = wrapped(*args, **kwargs)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/check/notebook.py"", line 226, in check', '    result = Checker.check(test_path, test_name, global_env)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/execute/checker.py"", line 73, in check', '    test = create_test_file(nb_or_test_path, test_name=test_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/otter/test_files/__init__.py"", line 52, in create_test_file', '    raise RuntimeError(f""Malformed test file: does not define the global variable \'{OK_FORMAT_VARNAME}\'"")', ""RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'""]"
18,SyntaxError,"unexpected EOF while parsing (<ipython-input-10-c7b7223ecd08>, line 1)",0,,2023-01-24 14:10:27.129373,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-10-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
19,NameError,name 'eleven' is not defined,0,,2023-01-24 14:10:27.200886,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-19-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
20,TypeError,unsupported operand type(s) for -: 'ellipsis' and 'ellipsis',0,,2023-01-24 14:10:27.570865,"[('difference = predicted_distance_m - estimated_distance_m', 24)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-28-ab13d160527e>"", line 24, in <module>', '    difference = predicted_distance_m - estimated_distance_m', ""TypeError: unsupported operand type(s) for -: 'ellipsis' and 'ellipsis'""]"
21,TypeError,unsupported operand type(s) for *: 'int' and 'ellipsis',0,,2023-01-24 14:11:01.928068,"[('manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', 11)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-32-206fddc8d3d3>"", line 11, in <module>', '    manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', ""TypeError: unsupported operand type(s) for *: 'int' and 'ellipsis'""]"
22,SyntaxError,"unexpected EOF while parsing (<ipython-input-8-c7b7223ecd08>, line 1)",0,,2023-01-24 14:39:53.715745,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-8-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
23,NameError,name 'eleven' is not defined,0,,2023-01-24 14:39:53.802583,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-17-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
24,TypeError,unsupported operand type(s) for -: 'ellipsis' and 'ellipsis',0,,2023-01-24 14:39:54.197590,"[('difference = predicted_distance_m - estimated_distance_m', 24)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-26-ab13d160527e>"", line 24, in <module>', '    difference = predicted_distance_m - estimated_distance_m', ""TypeError: unsupported operand type(s) for -: 'ellipsis' and 'ellipsis'""]"
25,SyntaxError,"unexpected EOF while parsing (<ipython-input-8-c7b7223ecd08>, line 1)",0,,2023-01-24 14:41:15.038889,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-8-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
26,NameError,name 'eleven' is not defined,0,,2023-01-24 14:41:15.170797,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-17-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
27,TypeError,unsupported operand type(s) for -: 'ellipsis' and 'ellipsis',0,,2023-01-24 14:41:15.656378,"[('difference = predicted_distance_m - estimated_distance_m', 24)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-26-6854fdc87eef>"", line 24, in <module>', '    difference = predicted_distance_m - estimated_distance_m', ""TypeError: unsupported operand type(s) for -: 'ellipsis' and 'ellipsis'""]"
28,TypeError,unsupported operand type(s) for *: 'int' and 'ellipsis',0,,2023-01-24 14:41:51.954124,"[('manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', 11)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-31-206fddc8d3d3>"", line 11, in <module>', '    manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', ""TypeError: unsupported operand type(s) for *: 'int' and 'ellipsis'""]"
29,SyntaxError,"unexpected EOF while parsing (<ipython-input-8-c7b7223ecd08>, line 1)",0,,2023-01-24 14:42:02.258239,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-8-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
30,NameError,name 'eleven' is not defined,0,,2023-01-24 14:42:02.480338,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-17-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
31,TypeError,unsupported operand type(s) for *: 'int' and 'ellipsis',0,,2023-01-24 14:42:02.952604,"[('manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', 11)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-30-206fddc8d3d3>"", line 11, in <module>', '    manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', ""TypeError: unsupported operand type(s) for *: 'int' and 'ellipsis'""]"
32,SyntaxError,"unexpected EOF while parsing (<ipython-input-8-c7b7223ecd08>, line 1)",0,,2023-01-25 10:56:04.426484,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3117, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""<ipython-input-8-c7b7223ecd08>"", line 1', '    print(""This line is missing something.""', '                                          ^', 'SyntaxError: unexpected EOF while parsing']"
33,NameError,name 'eleven' is not defined,0,,2023-01-25 10:56:04.527902,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-17-45c6a336eedf>"", line 1, in <module>', '    eleven + 8', ""NameError: name 'eleven' is not defined""]"
34,TypeError,unsupported operand type(s) for -: 'ellipsis' and 'ellipsis',0,,2023-01-25 10:56:05.105830,"[('difference = predicted_distance_m - estimated_distance_m', 24)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-26-ab13d160527e>"", line 24, in <module>', '    difference = predicted_distance_m - estimated_distance_m', ""TypeError: unsupported operand type(s) for -: 'ellipsis' and 'ellipsis'""]"
35,TypeError,unsupported operand type(s) for *: 'int' and 'ellipsis',0,,2023-01-25 10:57:11.393703,"[('manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', 11)]","['Traceback (most recent call last):', '  File ""/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3418, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""<ipython-input-30-206fddc8d3d3>"", line 11, in <module>', '    manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away', ""TypeError: unsupported operand type(s) for *: 'int' and 'ellipsis'""]"
36,SyntaxError,"incomplete input (1867411798.py, line 1)",0,,2023-09-03 18:38:37.351395,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""D:\\Software\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py"", line 3238, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File ""D:\\Software\\anaconda3\\Lib\\site-packages\\IPython\\core\\compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File ""C:\\Users\\ehven\\AppData\\Local\\Temp\\ipykernel_32408\\1867411798.py"", line 1', '    print(""This line is missing something.""', '                                           ^', 'SyntaxError: incomplete input']"
37,TypeError,'int' object is not callable,0,,2023-09-03 18:46:33.737979,"[('5*(3(10/11))-50(1/3)+2**(.5*22)-7/3+4', 1)]","['Traceback (most recent call last):', '  File ""D:\\Software\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py"", line 3505, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""C:\\Users\\ehven\\AppData\\Local\\Temp\\ipykernel_32408\\2162370792.py"", line 1, in <module>', '    5*(3(10/11))-50(1/3)+2**(.5*22)-7/3+4', '       ^^^^^^^^', ""TypeError: 'int' object is not callable""]"
38,TypeError,'int' object is not callable,0,,2023-09-03 18:46:58.695064,"[('5*(3+(10/11))-50(1/3)+2**(.5*22)-7/3+4', 1)]","['Traceback (most recent call last):', '  File ""D:\\Software\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py"", line 3505, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""C:\\Users\\ehven\\AppData\\Local\\Temp\\ipykernel_32408\\721614123.py"", line 1, in <module>', '    5*(3+(10/11))-50(1/3)+2**(.5*22)-7/3+4', '                  ^^^^^^^', ""TypeError: 'int' object is not callable""]"
39,NameError,name 'eleven' is not defined,0,,2023-09-03 18:52:38.089136,"[('eleven + 8', 1)]","['Traceback (most recent call last):', '  File ""D:\\Software\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py"", line 3505, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""C:\\Users\\ehven\\AppData\\Local\\Temp\\ipykernel_32408\\1097191323.py"", line 1, in <module>', '    eleven + 8', '    ^^^^^^', ""NameError: name 'eleven' is not defined""]"
